apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: redirect
  namespace: united-calendar
spec:
  secretName: redirect-tls
  commonName: calendar.unitedcycling.cc
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - calendar.unitedcycling.cc
